[system]
compiler = "gfortran"
fflags = "-cpp -DTIME -ffree-line-length-none -fbounds-check -fno-range-check"

[[target.exe]]
name = "cafemol"
sources = ["*.f90"]
# This is the same with the below line
# sources = ["main.f90", "myconst.f90"]
