[package]
name = "cafemake"
version = "0.1.0"
authors = ["Suguru Kato <salmon.bioinformatics@gmail.com>"]

[dependencies]
lazy_static = "1.1.0"
regex = "1.0"
serde = "1.0"
serde_derive = "1.0"
getopts = "0.2"
toml = "0.4"
